import { experiences } from "@/data/experience";
import type { Metadata } from "next";
import { PERSON_ID, SITE_URL, WEBSITE_ID, absoluteUrl, siteConfig } from "./site";

interface PageMetadataOptions {
  title: string;
  description: string;
  path: string;
  image?: { url: string; width?: number; height?: number; alt: string };
}

// Default social card generated by app/opengraph-image.tsx.
const defaultImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} - ${siteConfig.role}`,
};

// Per-page metadata with its own canonical + Open Graph URL. Child segments
// replace (not merge) the parent's openGraph/alternates, so every indexable
// page must go through this helper.
export function pageMetadata({ title, description, path, image = defaultImage }: PageMetadataOptions): Metadata {
  return {
    title: { absolute: title },
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_US",
      siteName: siteConfig.name,
      url: path,
      title,
      description,
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image.url],
    },
  };
}

const currentRole = experiences.find((exp) => exp.type === "work" && exp.current);

const alumniOf = experiences
  .filter((exp) => exp.type === "education")
  .map((exp) => ({ "@type": "EducationalOrganization", name: exp.company }));

export const personSchema = {
  "@type": "Person",
  "@id": PERSON_ID,
  name: siteConfig.name,
  alternateName: siteConfig.shortName,
  url: `${SITE_URL}/`,
  mainEntityOfPage: `${SITE_URL}/`,
  image: {
    "@type": "ImageObject",
    url: absoluteUrl(siteConfig.image.path),
    width: siteConfig.image.width,
    height: siteConfig.image.height,
    caption: siteConfig.image.alt,
  },
  jobTitle: siteConfig.jobTitle,
  description: siteConfig.description,
  email: `mailto:${siteConfig.email}`,
  address: {
    "@type": "PostalAddress",
    addressLocality: siteConfig.location.locality,
    addressCountry: siteConfig.location.country,
  },
  ...(currentRole && {
    worksFor: { "@type": "Organization", name: currentRole.company },
  }),
  alumniOf,
  knowsAbout: siteConfig.knowsAbout,
  sameAs: Object.values(siteConfig.social),
};

export const websiteSchema = {
  "@type": "WebSite",
  "@id": WEBSITE_ID,
  name: `${siteConfig.name} - Portfolio`,
  alternateName: siteConfig.shortName,
  url: `${SITE_URL}/`,
  description: `Professional portfolio of ${siteConfig.name}, Full-Stack and Front-End Developer.`,
  inLanguage: "en",
  author: { "@id": PERSON_ID },
  publisher: { "@id": PERSON_ID },
};

export function breadcrumbSchema(items: { name: string; path: string }[]) {
  return {
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}
